import os

ORGANIZATIONS_DIR_PATH = os.getenv("ORGANIZATIONS_DIR_PATH", "organizations")
ORGANIZATIONS_SLUG_FIELD_NAME = os.getenv("ORGANIZATIONS_SLUG_FIELD_NAME", "adres")
ORGANIZATIONS_NAME_FIELD_NAME = os.getenv("ORGANIZATIONS_NAME_FIELD_NAME", "nazwa")
