blank_issues_enabled: true
contact_links:
  - name: Zmiana listy produktów na stronie mojej organizacji
    url: https://github.com/wyslijco/wyslijco.github.io/wiki/Jak-aktualizowa%C4%87-produkty-w-wy%C5%9Blij.co%3F
    about: Zobacz, jak możesz dodać lub usunąć produkt ze strony swojej organizacji w Wyślij.co
