name: Zgłoszenie organizacji
description: Zgłoś swoją organizację do programu Wyślij.co
title: "[Nowa Organizacja]"
labels: ["organizacje", "nowa-organizacja"]
assignees: 
  - ivellios

body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za zainteresowanie dołączeniem do programu Wyślij.co. Wypełnij poniższe pola informacjami o swojej organizacji, żeby zgłosić ją do programu.
        # Podstawowe informacje
  - type: input
    id: nazwa
    attributes:
      label: Nazwa Twojej organizacji
    validations:
      required: true
  - type: input
    id: www
    attributes:
      label: Adres strony internetowej Twojej organizacji
    validations:
      required: true
  - type: input
    id: krs
    attributes:
      label: KRS przypisany do Twojej organizacji
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Konfiguracja strony w Wyślij.co
        Strona Twojej organizacji w Wyślij.co będzie dostępna pod adresem `wyslij.co/NAZWA_STRONY`. W tym celu potrzebujemy od Ciebie uproszczonej nazwy Twojej organizacji, **ze spacjami zamienionymi na myśliniki oraz bez polskich znaków diakrytycznych**. Najlepiej, jeżeli nazwa będzie wyrażona w celowniku tak, aby można było wypowiedzieć zdanie _"Wyślij co NAZWA_ORGANIZACJI"_; np. _"Wyślij co testowej"_, _"Wyślij co opiekunom potrzebujących"_. 
        Ułatwi to promowanie strony Twojej organizacji w programie Wyślij.co.

        **Oto kilka przykładów:**

        - **Nazwa organizacji** "Testowa"
          **Nazwa strony w celowniku**: `testowej`
          **Adres strony**: `wyslij.co/testowej`
          **Można czytać**: _"Wyślij co testowej"_
        - **Nazwa organizacji** "Wsparcie dla milusińskich" 
          **Nazwa strony w celowniku**: `wspierajacym-milusinskich`
          **Adres**: `wyslij.co/wspierajacym-milusinskich`
          **Można czytać**: _"Wyślj co wspierającym milusińskich"_
        - **Nazwa organizacji** "Zrób coś dobrego dla innych" 
          **Nazwa strony w celowniku** `robiacym-cos-dobrego-dla-innych`
          **Adres**: `wyslij.co/robiacym-cos-dobrego-dla-innych`
          **Można czytać**: _"Wyślij co robiącym coś dobrego dla innych"_

        Możesz zostać też po prostu przy nazwie organizacji i uprościć ją (sprawdzimy, czy nie pokrywa się z inną organizacją):

        - **Nazwa organizacji** "Zrób coś dobrego dla innych"
          **Nazwa strony**: `zrob-cos-dobrego`
          **Adres**: `wyslij.co/zrob-cos-dobrego`
        - **Nazwa organizacji** "Wesprzyj potrzebujące grupy"
          **Nazwa strony**: wesprzyj-grupy
          **Adres**: `wyslij.co/wesprzyj-grupy`

        **Uwaga!** Zastrzegamy sobie prawo do zmiany tej wartości w celu zapewnienia równego traktowania wszystkich organizacji korzystających z programu Wyślij.co.

  - type: input
    id: nazwa_strony
    attributes:
      label: Nazwa Twojej strony w Wyślij.co
      description: Wprowadź nazwę bez polskich znaków diakrytycznych, oraz spacjami zmienionymi na `-`
      placeholder: mojej-organizacji
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Dane teleadresowe do dostaw

        Podaj dane dla dostaw przesyłek do Twojej organizacji. Powinny to być oficjalne dane teleadresowe.
        Pamiętaj, że przekazane tutaj informacje będą publicznie dostępne na stronie Twojej organizacji
        w Wyślij.co.
  - type: input
    id: ulica
    attributes:
      label: Ulica i numer budynku/lokalu
    validations:
      required: true
  - type: input
    id: kod_pocztowy
    attributes:
      label: Kod Pocztowy
      description: Wprowadź kod pocztowy w formacie `00-000`
      placeholder: 00-000
    validations:
      required: true
  - type: input
    id: miasto
    attributes:
      label: Miasto
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Adres email dla firmy kurierskiej
      description: |
        Podaj oficjalny adres email, na który firma kurierska wyśle powiadomienia dotyczące przesyłki.
        Pamiętaj, że ten adres będzie publicznie widoczny w internecie.
      placeholder: nazwa@example.com
    validations:
      required: true
  - type: input
    id: telefon
    attributes:
      label: Telefon kontaktowy dla kuriera
      description: |
        Wprowadź numer telefonu w formacie `000 000 000`
        Podaj oficjalny numer telefonu, na który firma kurierska wyśle powiadomienia dotyczące przesyłki.
        Pamiętaj, że ten numer będzie publicznie widoczny w internecie.
      placeholder: 000 000 000
    validations:
      required: true
  - type: input
    id: kod_paczkomatu
    attributes:
      label: Kod paczkomatu
      description: |
        Podaj kod paczkomatu, w którym możesz odebrać przesyłki wysłane za pośrednictwem firmy InPost.
        Kod paczkomatu możesz znaleźć na stronie [Znajdź Paczkomat](https://inpost.pl/znajdz-paczkomat).
      placeholder: WAW01M
    validations:
      required: false
  - type: textarea
    id: dodatkowe_informacje
    attributes:
      label: Dodatkowe informacje dla dostawcy
      description: |
        Jeżeli to konieczne, podaj dodatkowe informacje do przekazania dla firmy dostawczej.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Następne kroki
        Po wypełnieniu formularza, Twój wniosek zostanie zweryfikowany przez nasz zespół. W celu weryfikacji poprawności danych skontaktujemy się z Twoją organizacją poprzez oficjalne dane kontaktowe dostępne na stronie internetowej organizacji lub w rejestrze KRS. W przypadku pozytywnej weryfikacji, otrzymasz od nas informację o dalszych krokach w komentarzu do tego zgłoszenia (zakładka Issues).
        Pamiętaj, że przekazane przez Ciebie dane powinny być informacjami oficjalnymi Twojej organizacji i będą dostępne publicznie w zgłoszeniu, kodzie oraz na stronach Wyślij.co.
