name: Przetwarzenie zgłoszenia organizacji

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  validate-form:
    if: contains(github.event.issue.labels.*.name, 'nowa-organizacja')
    name: Ekstrakcja danych z formularza
    runs-on: ubuntu-latest
    outputs:
      payload: ${{ steps.parse.outputs.payload }}
    steps:
      - name: Parsowanie treści zgłoszenia
        id: parse
        uses: onmax/issue-form-parser@v1.5
        with:
          issue_number: ${{ github.event.issue.number }}

  processing:
    if: contains(github.event.issue.labels.*.name, 'nowa-organizacja')
    needs: [validate-form]
    name: Przetwarzenie zgłoszenia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        working-directory: ./.github/scripts
        run: pip install -r requirements.txt
      - name: Run script
        env:
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_FORM_JSON: ${{ needs.validate-form.outputs.payload }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PAT: ${{ secrets.CUSTOM_GITHUB_PAT }}
        working-directory: ./.github/scripts
        run: python cli.py

